### ISSUE TITLE
Any recommended way to make getters?

### ISSUE THREAD

**Issue by Derek-X-Wang** [twittemb/RxReduce#2]
Hi @twittemb,

Thanks for this awesome lib :)

I would like to get the current substate. Not via state() driver.

The stateSubject is private. Any recommended way to obtain current state?

Thanks,
Derek

**Comment by twittemb** [comment]
Hi @Derek-X-Wang 

Thanks for your feedback. What is the aim of what you're trying to do ?

RxReduce is meant to be reactive oriented, so as the state is a Driver, which is a wrapper of BehaviourRelay, when you subscribe to it you will get the last value it has. This is somehow an equivalent to getting directly the inner value of the state.

Is that something that would be acceptable for you ?

**Comment by Derek-X-Wang** [comment]
Thanks for your reply @twittemb :)

So my case is that I have a dynamic collection view for the menu.

And the onclick behavior is changed based on the current RxReduce state.

Just don't know how to do it in a reactive way.

if I use combineLatest for collectionView.rx.itemSelected and substate driver. The menu is triggered every time when the state change. I only want to trigger it when the item is clicked.

if I use withLastestFrom for collectionView.rx.itemSelected and substate driver. I will lose the IndexPath param from itemSelected.

I want to access the current state when I subscribe collectionView.rx.itemSelected. Right now, I just save a current tab variable inside the class and update it when the sub state change.

But I feel I don't need it since it's in the state already and this side effect may cause bugs later.

**Comment by Derek-X-Wang** [comment]
Nevermind, just know there is an overloaded version of withLatestFrom that can do my stuff...

My bad
