### ISSUE TITLE
Documentation is not up to date with 0.7

### ISSUE THREAD

**Issue by dp-1a** [twittemb/RxReduce#3]
Hi,

the README and the example project do not reflect the latest changes on the library, any plans on updating them?

Also the changes seem quite "major" in between the version, in future do you expect more breaking changes, or do you feel like the implementation is stable now?

Regards
Daniel

**Comment by twittemb** [comment]
Hi @dp-1a 

The README is now up to date. Indeed, the changes were pretty "major", for the good of the "Rx" philosophy. There is no plan to modify it in a breaking way in the future to come.

thanks for your feedback.
